# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: b63af35986f4762c635f6ae7b3abbfd286ab386e18c00abd829ca0181d096d3218568634990000eaa3260a11cf776f2c9552719b2b32a3f14c1f58980fa219c2

test:
  secret_key_base: 9e14d205fac60c6b3bdd37e5061bfc4eede7581a11503fab0a3208817726e33b55b4dabe77810d84bf6123d5c058b0d884a189c9437f95d12233dc779b40e2cf

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
